# Reactor Kinetics Example 

Jialu Wang (jwang44@nd.edu) and Alex Dowling (adowling@nd.edu)

University of Notre Dame

This notebook conducts design of experiments for a reactor kinetics experiment with the Pyomo.DOE.
    

## Step 0: Import Pyomo and Pyomo.DOE module

In [1]:
import matplotlib.pyplot as plt
from pyomo.environ import *
from pyomo.dae import *

import numpy as np
#from scipy.interpolate import interp2d
import pandas as pd 
#from itertools import permutations, product, combinations
import idaes

from fim_doe import *

## Step 1: Import Reaction Example Mathematical Model

Consider two chemical reactions that converts molecule $A$ to desired product $B$ and a less valuable side-product $C$.

$A \overset{k_1}{\rightarrow} B \overset{k_2}{\rightarrow} C$

Our ultimate goals is to design a large-scale continous reactor that maximizes the production of $B$. This general sequential reactions problem is widely applicable to CO$_2$ capture and industry more broadly (petrochemicals, pharmasuticals, etc.).

The rate laws for these two chemical reactions are:

$r_A = -k_1 C_A$

$r_B = k_1 C_A - k_2 C_B$

$r_C = k_2 C_B$

Here, $C_A$, $C_B$, and $C_C$ are the concentrations of each species. The rate constants $k_1$ and $k_2$ depend on temperature as follows:

$k_1 = A_1 \exp{\frac{-E_1}{R T}}$

$k_2 = A_2 \exp{\frac{-E_2}{R T}}$

$A_1, A_2, E_1$, and $E_2$ are fitted model parameters. $R$ is the ideal-gas constant and $T$ is absolute temperature.

Using the **CCSI$^2$ toolset**, we would like do the following perform:

Perform **uncertainty quantification** and **design of experiments** on a small-scale **batch reactor** to infer parameters $A_1$, $A_2$, $E_1$, and $E_2$.

### Batch reactor

The concenrations in a batch reactor evolve with time per the following differential equations:

$$ \frac{d C_A}{dt} = r_A = -k_1 C_A $$

$$ \frac{d C_B}{dt} = r_B = k_1 C_A - k_2 C_B $$

$$ \frac{d C_C}{dt} = r_C = k_2 C_B $$

This is a linear system of differential equations. Assuming the feed is only species $A$, i.e., 

$$C_A(t=0) = C_{A0} \quad C_B(t=0) = 0 \quad C_C(t=0) = 0$$

When the temperature is constant, it leads to the following analytic solution:

$$C_A(t) = C_{A,0} \exp(-k_1 t)$$

$$C_B(t) = \frac{k_1}{k_2 - k_1} C_{A,0} \left[\exp(-k_1 t) - \exp(-k_2 t) \right]$$

$$C_C(t) = C_{A,0} - \frac{k_2}{k_2 - k_1} C_{A,0} \exp(-k_1 t) + \frac{k_1}{k_2 - k_1} \exp(-k_2 t) C_{A,0} = C_{A,0} - C_{A}(t) - C_{B}(t)$$

In [2]:
from reactor_kinetics import *

## Step 2: Define inputs

In [3]:
# Create model function
createmod = create_model

# discretization by Pyomo.DAE
disc = disc_for_measure

# Control time set [h]
t_control = [0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1]
    
# Measurement time points [h]
t_measure = [0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1]

# design variable and its control time set
dv_pass = {'CA0': [0],'T': t_control}
    
# Create measurement object
measure_pass = {'C':{'CA': t_measure, 'CB': t_measure, 'CC': t_measure}}
measure_class =  Measurements(measure_pass)

# Define parameter nominal value 
parameter_dict = {'A1': 84.79085853498033, 'A2': 371.71773413976416, 'E1': 7.777032028026428, 'E2': 15.047135137500822}

All measurements are flattened.
Flatten measurement name: ['C_index_CA', 'C_index_CB', 'C_index_CC']


In [4]:
def generate_exp(t_set, CA0, T):  
    '''Generate experiments. 
    t_set: time control set for T.
    CA0: CA0 value
    T: A list of T 
    '''
    assert(len(t_set)==len(T)), 'T should have the same length as t_set'
    
    T_con_initial = {}
    for t, tim in enumerate(t_set):
        T_con_initial[tim] = T[t]
        
    dv_dict_overall = {'CA0': {0: CA0},'T': T_con_initial}
    return dv_dict_overall

In [5]:
# empty prior
prior_all = np.zeros((4,4))


# add prior information
#prior_5_300 = pd.read_csv('fim_5_300_scale.csv')
#prior_5_300_500 = pd.read_csv('fim_5_300_500_scale.csv')

#prior_all = prior_5_300


prior_pass=np.asarray(prior_all)

#L_initials = np.linalg.cholesky(prior_pass)
#print(L_initials)

print('The prior information FIM:', prior_pass)
print('Prior Det:', np.linalg.det(prior_pass))
print('Eigenvalue of the prior experiments FIM:', np.linalg.eigvals(prior_pass))
print('Eigenvalue of the prior experiments FIM:', np.linalg.eigh(prior_pass)[1])

The prior information FIM: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Prior Det: 0.0
Eigenvalue of the prior experiments FIM: [0. 0. 0. 0.]
Eigenvalue of the prior experiments FIM: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Method: Compute FIM 

This method computes an MBDoE optimization problem with no Degree of Freedom.

In [6]:
# choose from 'sequential_finite', 'direct_kaug'
# 'sequential_sipopt', 'sequential_kaug' is also available
sensi_opt = 'sequential_finite'
#sensi_opt = 'direct_kaug'

# model option
if sensi_opt == 'direct_kaug':
    args_ = [False]
else:
    args_ = [True]
    

# Define experiments
exp1 = generate_exp(t_control, 5, [570, 300, 300, 300, 300, 300, 300, 300, 300])

In [7]:
doe_object = DesignOfExperiments(parameter_dict, dv_pass,
                                 measure_class, createmod,
                                prior_FIM=prior_pass, discretize_model=disc, args=args_)


result = doe_object.compute_FIM(exp1,mode=sensi_opt, FIM_store_name = 'dynamic.csv', 
                                store_output = 'store_output', read_output=None,
                                formula='central')


result.calculate_FIM(doe_object.design_values)


This scenario: {'A1': {0: 84.8756493935153}, 'A2': {0: 371.71773413976416}, 'E1': {0: 7.777032028026428}, 'E2': {0: 15.047135137500822}, 'jac-index': {'A1': [0], 'A2': [0], 'E1': [0], 'E2': [0]}, 'eps-abs': {'A1': 0.0848756493935153, 'A2': 0.37171773413976417, 'E1': 0.007777032028026428, 'E2': 0.015047135137500823}, 'scena-name': [0]}
Ipopt 3.13.2: linear_solver=ma57
halt_on_ampl_error=yes
max_iter=3000


******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt

This version of Ipopt was compiled from source code available at
    https://github.com/IDAES/Ipopt as part of the Institute for the Design of
    Advanced Energy Systems Process Systems Engineering Framework (IDAES PSE
    Framework) Copyright (c) 2018-2019. See https://github.com/

Output this time:  [5.0, 0.6706243700020834, 0.4195560837359151, 0.2624827180069096, 0.16421446362737377, 0.10273586874285646, 0.06427362421801934, 0.04021087104893356, 0.02515672906555432, 0.0, 1.4356608195123035, 1.5205901724705073, 1.5079974275825079, 1.4413335440984965, 1.347049388125238, 1.241037622436591, 1.1326547091791959, 1.027229845637414, 0.0, 2.8937148104856125, 3.0598537437935778, 3.229519854410583, 3.39445199227413, 3.5502147431319058, 3.69468875334539, 3.8271344197718706, 3.947613425297032]
This scenario: {'A1': {0: 84.79085853498033}, 'A2': {0: 371.71773413976416}, 'E1': {0: 7.784809060054453}, 'E2': {0: 15.047135137500822}, 'jac-index': {'A1': [0], 'A2': [0], 'E1': [0], 'E2': [0]}, 'eps-abs': {'A1': 0.08479085853498033, 'A2': 0.37171773413976417, 'E1': 0.007784809060054453, 'E2': 0.015047135137500823}, 'scena-name': [0]}
Ipopt 3.13.2: linear_solver=ma57
halt_on_ampl_error=yes
max_iter=3000


******************************************************************************

Output this time:  [5.0, 0.6706243700020836, 0.4195560837359153, 0.2624827180069097, 0.16421446362737382, 0.10273586874285653, 0.06427362421801941, 0.04021087104893361, 0.02515672906555436, 0.0, 1.441416665040551, 1.5268448073993228, 1.514721262165308, 1.4484455916701346, 1.3544479171661528, 1.248617623361608, 1.1403173456620836, 1.03488709459508, 0.0, 2.887958964957366, 3.0535991088647614, 3.222796019827782, 3.3873399447024912, 3.542816214090991, 3.687108752420372, 3.819471783288983, 3.939956176339366]
This scenario: {'A1': {0: 84.70606767644534}, 'A2': {0: 371.71773413976416}, 'E1': {0: 7.777032028026428}, 'E2': {0: 15.047135137500822}, 'jac-index': {'A1': [0], 'A2': [0], 'E1': [0], 'E2': [0]}, 'eps-abs': {'A1': 0.08470606767644534, 'A2': 0.37171773413976417, 'E1': 0.007777032028026428, 'E2': 0.015047135137500823}, 'scena-name': [0]}
Ipopt 3.13.2: linear_solver=ma57
halt_on_ampl_error=yes
max_iter=3000


******************************************************************************
T

Output this time:  [5.0, 0.6706243700020837, 0.4195560837359155, 0.26248271800690987, 0.16421446362737402, 0.10273586874285656, 0.06427362421801945, 0.04021087104893362, 0.02515672906555435, 0.0, 1.4384112269396816, 1.5233649787335601, 1.5108005401811877, 1.4441529235617967, 1.3498659292064588, 1.243830257365472, 1.135403210540418, 1.029916244982974, 0.0, 2.890964403058235, 3.0570789375305245, 3.2267167418119023, 3.3916326128108296, 3.547398202050685, 3.691896118416508, 3.8243859184106483, 3.9449270259514715]
This scenario: {'A1': {0: 84.79085853498033}, 'A2': {0: 371.71773413976416}, 'E1': {0: 7.769254995998401}, 'E2': {0: 15.047135137500822}, 'jac-index': {'A1': [0], 'A2': [0], 'E1': [0], 'E2': [0]}, 'eps-abs': {'A1': 0.08479085853498033, 'A2': 0.37171773413976417, 'E1': 0.0077692549959984016, 'E2': 0.015047135137500823}, 'scena-name': [0]}
Ipopt 3.13.2: linear_solver=ma57
halt_on_ampl_error=yes
max_iter=3000


*************************************************************************

Output this time:  [5.0, 0.670624370002084, 0.41955608373591563, 0.2624827180069099, 0.16421446362737396, 0.10273586874285658, 0.06427362421801945, 0.040210871048933616, 0.02515672906555434, 0.0, 1.4326573615440616, 1.5171119900116485, 1.5040785376836843, 1.4370435698520607, 1.342471604700488, 1.2362565062752762, 1.1277492573498347, 1.0222703526130221, 0.0, 2.8967182684538546, 3.0633319262524363, 3.2334387443094053, 3.398741966520566, 3.554792526556655, 3.699469869506704, 3.8320398716012316, 3.9525729183214233]
Build time with sequential_finite mode [s]: 0.0396122932434082
Solve time with sequential_finite mode [s]: 0.9610984325408936
Total wall clock time [s]: 1.5833582878112793
Existed information has been added.
FIM: [[ 2.45738410e-03  5.94863782e-04 -4.56435589e-02 -6.00876165e-02]
 [ 5.94863782e-04  2.22810780e-04 -1.03935357e-02 -2.23273539e-02]
 [-4.56435589e-02 -1.03935357e-02  8.61211473e-01  1.05437230e+00]
 [-6.00876165e-02 -2.23273539e-02  1.05437230e+00  2.27036487e+00]]
T

In [8]:
mod_eg = doe_object.models[0]

t_list = []
for t in mod_eg.t:
    t_list.append(t)
    
print('kp1:')
for i in t_list:
    print(value(mod_eg.kp1[0,i]))
    
print('kp2:')
for i in t_list:
    print(value(mod_eg.kp2[0,i]))
    
print('CA:')
for i in t_list:
    print(value(mod_eg.C[0,'CA',i]))
    
print('CB:')
for i in t_list:
    print(value(mod_eg.C[0,'CB',i]))
    
print('CC:')
for i in t_list:
    print(value(mod_eg.C[0,'CC',i]))

kp1:
16.447958186505904
16.447958186505904
16.447958186505904
16.447958186505904
16.447958186505904
16.447958186505904
16.447958186505904
16.447958186505904
16.447958186505904
16.447958186505904
16.447958186505904
16.447958186505904
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.7558478281198764
3.75584

In [9]:
print('======Result summary======')
print('Four design criteria log10() value:')
print('A-optimality:', np.log10(result.trace))
print('D-optimality:', np.log10(result.det))
print('E-optimality:', np.log10(result.min_eig))
print('Modified E-optimality:', np.log10(result.cond))

======Result summary======
Four design criteria log10() value:
A-optimality: 0.49613453997436285
D-optimality: -10.3118203437022
E-optimality: -5.553641798357302
Modified E-optimality: 6.006360465080967


## Method: Optimization
Gradient-based optimization with IPOPT with .optimize_doe()

This function solves twice: It solves the square version of the MBDoE problem firstly, and then unfixes the design variables as Degree of Freedoms and solves again. In this way the optimization problem can be well initialized. 

In [10]:
#exp1 = generate_exp(t_control, 5, [477.43, 300, 300, 300, 300, 300, 300, 300, 300])
exp1 = generate_exp(t_control, 5, [477.43, 300, 300, 300, 300, 300, 300, 300, 300])

In [12]:
from itertools import permutations, product
doe_object = DesignOfExperiments(parameter_dict, dv_pass,
                                 measure_class, createmod,
                                prior_FIM=prior_pass, discretize_model=disc, args=[True])

square_result, optimize_result= doe_object.optimize_doe(exp1, if_optimize=True, if_Cholesky=True, 
                                                         scale_nominal_param_value=True, objective_option='det', 
                                                         L_initial=None)

#square_result = doe_object.optimize_doe(exp1, if_optimize=False, if_Cholesky=True, 
#                                                         scale_nominal_param_value=True, objective_option='det', 
#                                                         L_initial=None)

Sensitivity information is scaled by its corresponding parameter nominal value.
    'pyomo.core.base.objective.ScalarObjective'>) on block unknown with a new
    Component (type=<class 'pyomo.core.base.objective.ScalarObjective'>). This
    is usually indicative of a modelling error. To avoid this warning, use
    block.del_component() and block.add_component().
Ipopt 3.13.2: linear_solver=ma57
halt_on_ampl_error=yes
max_iter=3000


******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt

This version of Ipopt was compiled from source code available at
    https://github.com/IDAES/Ipopt as part of the Institute for the Design of
    Advanced Energy Systems Process Systems Engineering Framework (IDAES PSE
    Framework) Copyright (c) 2018-2

Reallocating memory for MA57: lfact (513180)
Reallocating memory for MA57: lfact (962390)
Reallocating memory for MA57: lfact (1058577)
  11  1.3743846e+01 8.41e+05 9.90e+06  -1.0 2.76e+04  -0.0 3.96e-04 4.49e-04h  1
Reallocating memory for MA57: lfact (2148001)
Reallocating memory for MA57: lfact (2480350)
  12  1.4067657e+01 8.41e+05 1.30e+07  -1.0 6.79e+04   0.4 3.60e-04 1.05e-04h  1
  13r 1.4067657e+01 8.41e+05 9.99e+02   5.2 0.00e+00   0.8 0.00e+00 3.43e-07R  4
  14r 6.2870147e+00 8.41e+05 2.22e+04   5.2 1.61e+08    -  5.15e-04 2.26e-05f  1
  15r 1.2703380e+01 8.40e+05 6.15e+04   4.5 1.10e+08    -  2.29e-01 4.80e-04f  1
  16  1.2622044e+01 8.26e+05 9.01e+02  -1.0 6.47e+05    -  2.08e-02 1.74e-02h  1
  17  1.2621332e+01 8.26e+05 9.01e+02  -1.0 3.82e+05    -  3.90e-02 2.10e-04h  1
  18  1.3775121e+01 7.35e+05 3.15e+05  -1.0 1.23e+06    -  2.63e-03 1.11e-01h  1
  19  2.2985944e+01 7.35e+05 3.14e+05  -1.0 1.50e+04   0.4 4.77e-04 7.18e-05h  1
iter    objective    inf_pr   inf_du lg(mu)

 106 -1.3503480e+01 9.59e+06 2.22e+05  -1.0 3.92e+03  -3.9 9.61e-02 2.81e-02w  1
 107 -1.3496035e+01 9.54e+06 2.21e+05  -1.0 6.91e+03  -4.3 2.04e-02 5.67e-03w  1
 108 -1.7757875e+01 1.41e+05 2.42e+05  -1.0 2.53e+03  -3.9 1.00e+00 5.88e-05h 11
 109 -1.7767475e+01 1.41e+05 2.42e+05  -1.0 4.82e+04    -  5.91e-02 1.11e-03h  5
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
 110 -1.7776588e+01 1.41e+05 2.42e+05  -1.0 4.73e+05    -  4.18e-02 1.75e-04h 12
 111 -1.7784699e+01 1.41e+05 2.42e+05  -1.0 5.08e+05    -  1.70e-01 8.53e-05h 13
 112 -1.7790213e+01 1.41e+05 2.42e+05  -1.0 5.45e+05    -  1.73e-02 4.17e-05h 14
 113 -1.7803351e+01 1.41e+05 2.42e+05  -1.0 6.06e+05    -  4.47e-01 6.42e-05h 13
 114 -1.7803682e+01 1.41e+05 2.41e+05  -1.0 6.96e+03  -4.4 5.24e-02 1.10e-04h  8
 115 -1.7804049e+01 1.41e+05 2.41e+05  -1.0 7.13e+03  -4.9 1.05e-01 5.11e-05h  9
 116 -1.7714813e+01 1.40e+05 2.40e+05  -1.0 5.45e+03  -3.5 4.99e-03 4.99e-03s 15
 117 -1.7717883e+01 1.40e+05

 202 -7.7902829e+00 9.94e+04 1.08e+05  -1.0 7.51e+04  -5.9 7.08e-02 3.42e-04h 11
 203 -7.8004179e+00 9.94e+04 1.08e+05  -1.0 1.88e+05  -6.4 4.54e-02 1.35e-04h 11
 204 -7.8097401e+00 9.94e+04 1.08e+05  -1.0 8.13e+04  -6.0 3.09e-01 3.53e-04h 11
 205 -7.9787159e+00 9.93e+04 1.08e+05  -1.0 7.04e+05  -6.4 7.42e-03 6.82e-04h  7
 206 -7.9823683e+00 9.93e+04 1.08e+05  -1.0 6.76e+04  -6.0 1.28e-01 2.25e-04h 11
 207 -7.9839690e+00 9.93e+04 1.08e+05  -1.0 2.72e+04  -5.6 9.22e-02 2.20e-04h 11
 208 -7.9858182e+00 9.93e+04 1.08e+05  -1.0 9.83e+04  -6.1 8.99e-02 7.40e-05h 12
 209 -7.9854514e+00 9.93e+04 1.08e+05  -1.0 3.74e+04  -5.6 6.75e-01 2.03e-04h 11
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
 210 -7.9801636e+00 9.92e+04 1.08e+05  -1.0 1.78e+05  -6.1 1.30e-01 2.43e-04h  8
 211r-7.9801636e+00 9.92e+04 1.00e+03   4.6 0.00e+00  -5.7 0.00e+00 3.00e-07R 20
 212r-1.0573609e+01 9.92e+04 9.98e+02   4.6 3.74e+07    -  1.08e-03 9.98e-04f  1
 213 -1.7545816e+00 9.18e+04

 296 -1.8715497e+01 4.86e+04 1.85e+06  -1.0 1.74e+03   0.0 8.21e-02 2.08e-03h  5
 297 -1.8777885e+01 4.86e+04 1.85e+06  -1.0 9.40e+03  -0.4 1.55e-03 8.93e-05h  6
 298 -1.8903843e+01 4.85e+04 1.85e+06  -1.0 2.07e+03  -0.0 1.45e-01 8.55e-04h  6
 299 -1.9084070e+01 4.85e+04 1.85e+06  -1.0 7.31e+03  -0.5 2.14e-03 2.10e-04h  7
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
 300 -1.9277120e+01 4.85e+04 1.86e+06  -1.0 2.27e+03  -0.1 8.29e-02 9.80e-04h  7
 301 -1.7295321e+01 8.59e+04 9.75e+06  -1.0 1.23e+04  -0.5 1.57e-03 1.67e-02w  1
 302 -1.8024500e+01 6.25e+04 7.33e+07  -1.0 7.04e+02  -0.1 4.58e-01 2.83e-01w  1
 303 -1.8062598e+01 6.22e+04 7.29e+07  -1.0 9.51e+03  -0.6 1.31e-02 4.75e-03w  1
 304 -1.9605272e+01 4.85e+04 1.86e+06  -1.0 2.19e+05    -  1.57e-03 2.61e-04h  6
 305 -1.9749943e+01 4.84e+04 1.86e+06  -1.0 2.95e+03  -0.2 3.68e-01 6.14e-04h  8
 306 -1.9836233e+01 4.84e+04 1.88e+06  -1.0 1.70e+03   0.3 2.71e-02 8.45e-04h  9
 307 -2.0050790e+01 4.84e+04

 389 -2.3806452e+01 1.64e+06 1.80e+04  -1.0 7.83e+02   0.6 5.58e-03 1.88e-03h  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
 390 -2.3775992e+01 1.64e+06 1.80e+04  -1.0 1.15e+03   0.1 1.76e-02 1.23e-04h  1
 391 -1.4570425e+01 1.62e+06 5.93e+04  -1.0 1.24e+03  -0.3 3.12e-02 7.84e-03h  1
 392 -1.1636240e+01 1.62e+06 6.83e+04  -1.0 2.78e+03  -0.8 3.94e-02 2.96e-03h  1
 393 -1.1634160e+01 1.62e+06 6.83e+04  -1.0 3.25e+03  -1.3 3.92e-02 5.85e-05h  1
 394 -1.0890311e+01 1.61e+06 1.04e+05  -1.0 4.15e+03  -0.9 1.24e-01 4.28e-03h  1
 395 -3.7419114e+00 1.46e+06 1.22e+07  -1.0 4.50e+03  -1.3 5.30e-02 9.94e-02h  1
 396 -3.7442373e+00 1.36e+06 1.81e+07  -1.0 4.54e+03  -0.9 4.23e-01 7.14e-02h  1
 397 -3.7172987e+00 1.30e+06 2.42e+07  -1.0 3.69e+03  -0.5 3.31e-01 4.66e-02h  1
 398 -3.6879910e+00 1.22e+06 2.39e+07  -1.0 2.53e+03  -1.0 2.71e-01 6.76e-02h  1
 399 -3.6870117e+00 1.22e+06 2.39e+07  -1.0 2.75e+03  -1.4 4.65e-01 9.89e-04h  1
iter    objective    inf_pr 

 483 -1.3776958e+01 1.97e+04 2.35e+10  -1.0 8.15e+00   8.7 2.74e-02 1.17e-02h  1
 484 -1.3777613e+01 1.97e+04 2.35e+10  -1.0 8.06e+00   9.2 1.25e-01 1.07e-03h  1
 485 -1.3778141e+01 1.96e+04 2.35e+10  -1.0 2.45e+01   8.7 3.53e-03 8.79e-04h  1
 486 -1.3813340e+01 1.85e+04 2.27e+10  -1.0 8.05e+00   9.1 2.29e-01 6.06e-02h  1
 487 -1.3814602e+01 1.84e+04 2.27e+10  -1.0 7.57e+00   9.5 3.49e-02 2.39e-03h  1
 488 -1.3818691e+01 1.83e+04 2.26e+10  -1.0 7.55e+00   9.1 5.48e-02 7.48e-03h  1
 489 -1.3868060e+01 1.65e+04 2.27e+10  -1.0 7.49e+00   9.5 2.88e-01 1.01e-01h  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
 490 -1.3871939e+01 1.63e+04 2.25e+10  -1.0 6.75e+00   9.0 2.01e-01 8.40e-03h  1
 491 -1.3889715e+01 1.57e+04 2.24e+10  -1.0 6.69e+00   9.4 8.34e-01 4.10e-02h  1
 492 -1.3909176e+01 1.50e+04 2.16e+10  -1.0 6.42e+00   9.0 4.98e-02 4.67e-02h  1
 493 -1.3911242e+01 1.49e+04 2.15e+10  -1.0 6.13e+00   9.4 4.75e-03 5.28e-03h  1
 494 -1.3912389e+01 1.48e+04

 577 -1.7263666e+01 1.16e+05 1.32e+14  -1.0 4.55e+01  12.2 1.00e+00 1.00e+00h  1
 578 -7.4045210e+00 1.52e+05 2.66e+13  -1.0 1.53e+01  11.7 1.00e+00 7.98e-01h  1
 579 -5.2199433e+00 1.41e+05 1.30e+13  -1.0 1.76e+01  11.3 1.00e+00 5.05e-01h  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
 580 -5.1971188e+00 1.41e+05 1.28e+13  -1.0 5.92e+01  10.8 1.00e+00 1.09e-02h  1
 581 -5.1969774e+00 1.41e+05 1.28e+13  -1.0 1.77e+02  10.3 1.00e+00 6.84e-05h  1
 582 -5.1967738e+00 1.41e+05 1.28e+13  -1.0 5.22e+02   9.8 1.09e-01 1.01e-04h  1
 583 -5.1866709e+00 1.41e+05 1.28e+13  -1.0 1.49e+03   9.4 9.33e-02 5.25e-03h  1
 584 -5.1864423e+00 1.41e+05 1.28e+13  -1.0 5.85e+02   9.8 5.97e-01 1.14e-04h  1
 585 -5.1821187e+00 1.41e+05 1.27e+13  -1.0 1.66e+03   9.3 7.38e-02 2.29e-03h  1
 586 -5.1681306e+00 1.41e+05 1.26e+13  -1.0 6.56e+02   9.7 1.18e-01 7.01e-03h  1
 587 -5.1524617e+00 1.40e+05 1.25e+13  -1.0 1.85e+03   9.2 9.88e-02 8.46e-03h  1
 588 -5.1454537e+00 1.40e+05

 675 -1.8300196e+01 7.46e+05 2.94e+03  -1.0 1.04e+05    -  5.75e-01 6.25e-02h  5
 676 -1.6933812e+01 7.46e+05 1.28e+09  -1.0 2.98e+03   7.2 1.19e-01 3.18e-04h  2
 677 -1.6806073e+01 7.46e+05 1.34e+09  -1.0 2.98e+03   6.7 6.78e-01 1.10e-04h  5
 678 -1.6790595e+01 7.45e+05 3.14e+09  -1.0 2.98e+03   6.2 7.71e-01 1.14e-03h  8
 679 -1.6637420e+01 6.22e+05 1.40e+13  -1.0 2.98e+03   5.8 1.47e-01 1.74e-01h  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
 680 -1.6642829e+01 6.21e+05 1.40e+13  -1.0 2.57e+03   6.2 2.94e-01 1.26e-03h  1
 681 -1.6643046e+01 6.21e+05 1.40e+13  -1.0 2.61e+03   5.7 1.05e-01 1.33e-05h  1
 682 -1.6636434e+01 6.21e+05 1.40e+13  -1.0 3.26e+03   6.1 1.93e-01 2.57e-05h  1
 683 -7.4152153e+00 6.09e+05 1.37e+13  -1.0 3.22e+03   5.7 2.77e-01 1.92e-02h  1
 684 -7.3615749e+00 5.97e+05 1.27e+13  -1.0 3.19e+03   6.1 2.41e-01 1.97e-02h  1
 685 -7.3614437e+00 5.97e+05 1.27e+13  -1.0 3.06e+03   5.6 1.34e-01 1.49e-04h  1
 686r-7.3614437e+00 5.97e+05

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
 770r-3.5616942e+01 6.06e+05 9.99e+02   5.6 0.00e+00   9.3 0.00e+00 9.29e-08R  2
 771r-3.5621603e+01 6.06e+05 6.15e+03   5.6 4.39e+08    -  1.72e-07 1.49e-05f  1
 772r-3.5640349e+01 6.05e+05 5.53e+03   3.5 4.31e+08    -  2.09e-02 1.00e-03f  1
 773 -3.2903386e+01 1.11e+07 5.88e+02  -1.0 1.52e+07    -  4.78e-02 6.06e-01h  1
 774 -3.2245697e+01 1.11e+07 1.33e+12  -1.0 1.48e+04   8.8 4.50e-01 2.15e-02h  1
 775 -3.2175613e+01 1.11e+07 2.97e+12  -1.0 1.77e+04   8.3 9.96e-05 7.09e-05h  1
 776r-3.2175613e+01 1.11e+07 9.99e+02   7.0 0.00e+00   7.9 0.00e+00 3.92e-07R  2
 777r-3.2176502e+01 1.10e+07 1.51e+06   7.0 7.56e+09    -  1.97e-03 3.60e-06f  1
 778r-2.8073295e+01 8.50e+06 1.51e+06   4.2 3.68e+09    -  5.47e-03 2.97e-03f  1
 779 -2.9735517e+01 7.40e+06 1.23e+02  -1.0 4.02e+06    -  1.69e-01 1.37e-01h  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
 780 -3.1671805e+01 6.89e+06

 866 -2.2065002e+01 2.29e+06 1.67e+02  -1.0 1.99e+07    -  1.00e+00 1.87e-04h 13
 867 -2.2070824e+01 2.29e+06 1.68e+02  -1.0 1.93e+07    -  7.46e-02 1.91e-04h 13
 868 -2.2076695e+01 2.29e+06 1.78e+02  -1.0 2.00e+07    -  5.40e-01 1.90e-04h 13
 869 -2.2082614e+01 2.29e+06 1.79e+02  -1.0 1.98e+07    -  7.94e-02 1.92e-04h 13
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
 870 -2.8802678e+01 4.44e+08 1.01e+03  -1.0 2.03e+07    -  1.00e+00 7.84e-01w  1
 871 -2.8803127e+01 4.44e+08 8.57e+14  -1.0 1.60e+05  12.9 4.48e-04 5.54e-06w  1
 872 -2.8556615e+01 3.02e+08 1.90e+21  -1.0 3.59e+03  17.8 9.92e-01 1.00e+00w  1
 873 -2.2088576e+01 2.29e+06 1.98e+02  -1.0 7.03e+03  17.3 1.00e+00 1.92e-04h 12
 874 -2.2094594e+01 2.29e+06 2.00e+02  -1.0 1.99e+07    -  7.27e-02 1.95e-04h 13
 875 -2.2100677e+01 2.29e+06 2.12e+02  -1.0 2.06e+07    -  5.33e-01 1.94e-04h 13
 876 -2.2106792e+01 2.28e+06 2.13e+02  -1.0 2.06e+07    -  7.74e-02 1.95e-04h 13
 877 -2.2112958e+01 2.28e+06

 962 -1.3199705e+01 3.90e+08 6.84e+16  -1.0 9.45e+03  15.1 9.90e-01 5.14e-03w  1
 963 -3.9867541e+00 3.90e+08 6.86e+16  -1.0 9.47e+03  14.7 1.00e+00 4.01e-05w  1
 964 -2.2504375e+01 2.26e+06 3.71e+03  -1.0 9.52e+03  14.2 4.95e-01 2.05e-04h 12
 965 -2.2510354e+01 2.26e+06 3.73e+03  -1.0 3.27e+07    -  7.15e-02 2.05e-04h 13
 966 -2.2516544e+01 2.25e+06 4.10e+03  -1.0 3.67e+07    -  1.00e+00 2.06e-04h 13
 967 -2.2522258e+01 2.25e+06 4.12e+03  -1.0 2.79e+07    -  6.65e-02 2.05e-04h 13
 968 -2.2528203e+01 2.25e+06 4.32e+03  -1.0 3.21e+07    -  4.94e-01 2.05e-04h 13
 969 -2.2534136e+01 2.25e+06 4.35e+03  -1.0 3.17e+07    -  7.15e-02 2.05e-04h 13
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
 970 -2.2540287e+01 2.25e+06 4.76e+03  -1.0 3.61e+07    -  1.00e+00 2.06e-04h 13
 971 -2.2545941e+01 2.25e+06 4.79e+03  -1.0 2.64e+07    -  6.64e-02 2.05e-04h 13
 972 -2.2551836e+01 2.25e+06 5.01e+03  -1.0 3.10e+07    -  4.94e-01 2.06e-04h 13
 973 -2.2557725e+01 2.25e+06

1057 -2.2950153e+01 2.22e+06 4.25e+04  -1.0 2.84e+07    -  4.92e-01 3.33e-04h 12
1058 -2.2959371e+01 2.22e+06 4.28e+04  -1.0 2.93e+07    -  7.30e-02 3.43e-04h 12
1059 -2.2969223e+01 2.22e+06 4.60e+04  -1.0 3.11e+07    -  1.00e+00 3.56e-04h 12
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
1060 -2.2977661e+01 2.22e+06 4.63e+04  -1.0 2.67e+07    -  7.00e-02 3.30e-04h 12
1061 -2.2986563e+01 2.22e+06 4.81e+04  -1.0 2.83e+07    -  4.92e-01 3.39e-04h 12
1062 -2.2995778e+01 2.22e+06 4.83e+04  -1.0 2.90e+07    -  7.44e-02 3.47e-04h 12
1063 -2.3005304e+01 2.21e+06 5.21e+04  -1.0 3.01e+07    -  1.00e+00 3.53e-04h 12
1064 -2.3014108e+01 2.21e+06 5.24e+04  -1.0 2.73e+07    -  7.06e-02 3.45e-04h 12
1065 -1.7624606e+01 1.63e+08 9.72e+04  -1.0 2.80e+07    -  4.92e-01 7.12e-01w  1
1066 -2.0462350e+01 4.83e+07 7.86e+19  -1.0 5.12e+03  16.4 3.18e-01 1.00e+00w  1
1067 -1.7153118e+01 9.74e+06 3.45e+19  -1.0 3.19e+03  15.9 9.90e-01 1.00e+00w  1
1068 -2.3023090e+01 2.21e+06

1152 -3.1874358e+01 1.14e+07 2.25e+08  -1.0 4.59e+06    -  9.44e-02 1.04e-03h 10
1153 -3.1897055e+01 1.14e+07 3.97e+08  -1.0 4.66e+06    -  1.00e+00 1.03e-03h 10
1154 -2.7035394e+01 1.23e+07 1.78e+10  -1.0 4.60e+06    -  4.57e-02 5.37e-01w  1
1155 -2.7038175e+01 1.23e+07 2.87e+11  -1.0 3.16e+05   6.2 1.31e-03 1.86e-06w  1
1156 -2.7190384e+01 1.23e+07 4.86e+11  -1.0 3.15e+05   5.7 1.24e-03 1.06e-04w  1
1157 -3.1938066e+01 1.14e+07 4.10e+08  -1.0 1.43e+03  11.6 4.57e-02 1.05e-03h  9
1158 -3.1986658e+01 1.14e+07 5.44e+08  -1.0 4.72e+06    -  4.38e-01 1.05e-03h 10
1159 -3.2056142e+01 1.13e+07 5.55e+08  -1.0 4.70e+06    -  2.94e-02 1.05e-03h 10
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
1160 -3.2137331e+01 1.13e+07 9.71e+08  -1.0 4.87e+06    -  1.00e+00 1.03e-03h 10
1161 -3.2348874e+01 1.13e+07 9.77e+08  -1.0 4.74e+06    -  1.34e-02 1.57e-03h  9
1162 -3.2989773e+01 1.13e+07 9.95e+08  -1.0 4.62e+06    -  3.76e-02 3.09e-03h  8
1163 -3.2939928e+01 1.13e+07

1249 -3.7167531e+01 7.23e+06 1.49e+02  -1.0 6.57e+06    -  4.77e-01 3.48e-03h  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
1250 -3.7165644e+01 7.20e+06 2.86e+02  -1.0 1.12e+07    -  5.12e-01 3.59e-03h  8
1251 -3.7170654e+01 7.14e+06 3.65e+02  -1.0 6.25e+06    -  5.06e-01 8.54e-03h  7
1252 -3.7172067e+01 7.13e+06 4.25e+02  -1.0 2.90e+06    -  5.43e-01 1.06e-03h 10
1253 -3.7172640e+01 7.13e+06 4.80e+02  -1.0 3.81e+06    -  5.40e-01 5.34e-04h 11
1254 -3.7172755e+01 7.13e+06 5.59e+02  -1.0 3.86e+06    -  7.46e-01 5.37e-04h 11
1255 -3.7172448e+01 7.12e+06 5.83e+02  -1.0 3.89e+06    -  1.97e-01 5.41e-04h 11
1256 -3.7172120e+01 7.12e+06 7.08e+02  -1.0 3.87e+06    -  9.36e-01 5.42e-04h 11
1257 -3.7171671e+01 7.11e+06 7.63e+02  -1.0 3.92e+06    -  3.09e-01 5.46e-04h 11
1258 -3.7171255e+01 7.11e+06 9.59e+02  -1.0 3.90e+06    -  1.00e+00 5.48e-04h 11
1259 -3.7170956e+01 7.11e+06 1.04e+03  -1.0 3.99e+06    -  3.00e-01 5.55e-04h 11
iter    objective    inf_pr 

1346 -3.6524003e+01 4.57e+06 6.74e+02  -1.0 1.55e+07    -  2.00e-01 2.17e-03h  9
1347 -3.6513787e+01 4.56e+06 6.96e+02  -1.0 1.56e+07    -  1.81e-01 2.24e-03h  9
1348 -3.6503919e+01 4.55e+06 7.15e+02  -1.0 1.69e+07    -  1.46e-01 2.12e-03h  9
1349 -3.6494730e+01 4.55e+06 7.33e+02  -1.0 2.07e+07    -  1.08e-01 1.76e-03h  9
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
1350 -3.3307914e+01 1.35e+07 9.65e+03  -1.0 3.73e+07    -  4.04e-02 2.59e-01w  1
1351 -3.3182646e+01 1.35e+07 1.82e+12  -1.0 5.64e+05   7.0 3.98e-06 1.68e-04w  1
1352 -3.2077102e+01 1.39e+07 1.90e+17  -1.0 6.99e+02  14.9 6.09e-01 1.00e+00w  1
1353 -3.6492763e+01 4.54e+06 7.47e+02  -1.0 4.07e+02  14.4 4.04e-02 2.53e-04h 10
1354 -3.6490873e+01 4.54e+06 7.74e+02  -1.0 4.51e+07    -  6.07e-02 2.21e-04h 11
1355 -3.6488988e+01 4.54e+06 7.93e+02  -1.0 4.18e+07    -  4.27e-02 2.63e-04h 11
1356 -3.6489089e+01 4.53e+06 3.02e+11  -1.0 3.03e+00  13.4 9.61e-01 3.71e-03h  1
1357r-3.6489089e+01 4.53e+06

1442 -3.7863633e+01 8.32e+05 3.74e+01  -1.0 7.78e+06    -  1.00e+00 1.95e-03h 10
1443 -3.7861539e+01 8.30e+05 3.71e+01  -1.0 7.76e+06    -  1.00e+00 1.95e-03h 10
1444 -3.7859473e+01 8.28e+05 3.69e+01  -1.0 7.74e+06    -  1.00e+00 1.95e-03h 10
1445 -3.4011529e+01 8.64e+06 2.25e+02  -1.0 7.72e+06    -  1.00e+00 1.00e+00w  1
1446 -3.4884881e+01 6.28e+06 4.18e+02  -1.0 3.32e+06    -  5.25e-01 2.81e-01w  1
1447 -3.5399962e+01 5.12e+06 3.40e+02  -1.0 1.01e+06    -  3.00e-01 1.95e-01w  1
1448 -3.7857440e+01 8.27e+05 3.66e+01  -1.0 1.97e+04   8.7 1.00e+00 1.95e-03h  9
1449 -3.7855438e+01 8.25e+05 3.64e+01  -1.0 7.69e+06    -  1.00e+00 1.95e-03h 10
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
1450 -3.7853471e+01 8.24e+05 3.63e+01  -1.0 7.67e+06    -  1.00e+00 1.95e-03h 10
1451 -3.7851534e+01 8.22e+05 3.61e+01  -1.0 7.64e+06    -  1.00e+00 1.95e-03h 10
1452 -3.7849633e+01 8.20e+05 3.60e+01  -1.0 7.62e+06    -  1.00e+00 1.95e-03h 10
1453 -3.7847763e+01 8.19e+05

1535 -3.7780954e+01 7.23e+05 3.17e+01  -1.0 6.03e+06    -  7.17e-01 1.95e-03h 10
1536 -3.3530320e+01 7.58e+06 2.48e+02  -1.0 6.01e+06    -  1.00e+00 1.00e+00w  1
1537 -3.0796123e+01 4.71e+06 2.45e+03  -1.0 3.59e+06    -  2.15e-01 3.91e-01w  1
1538 -3.2969441e+01 4.33e+06 2.25e+03  -1.0 6.90e+05    -  5.58e-02 8.22e-02w  1
1539 -3.7780569e+01 7.22e+05 3.17e+01  -1.0 6.40e+05    -  1.00e+00 1.95e-03h  9
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
1540 -3.7780198e+01 7.20e+05 3.16e+01  -1.0 5.99e+06    -  7.14e-01 1.95e-03h 10
1541 -3.7779849e+01 7.19e+05 3.16e+01  -1.0 5.97e+06    -  1.00e+00 1.95e-03h 10
1542 -3.7779513e+01 7.18e+05 3.15e+01  -1.0 5.95e+06    -  7.11e-01 1.95e-03h 10
1543 -3.7779199e+01 7.16e+05 3.15e+01  -1.0 5.93e+06    -  1.00e+00 1.95e-03h 10
1544 -3.7778898e+01 7.15e+05 3.14e+01  -1.0 5.90e+06    -  7.08e-01 1.95e-03h 10
1545 -3.7778618e+01 7.13e+05 3.13e+01  -1.0 5.88e+06    -  1.00e+00 1.95e-03h 10
1546 -3.7778352e+01 7.12e+05

1629 -2.0659329e+01 4.04e+06 5.43e+11  -1.0 2.08e+05   5.7 5.46e-04 3.00e-03w  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
1630 -3.7793928e+01 6.30e+05 3.01e+01  -1.0 2.12e+05   6.1 1.00e+00 1.95e-03h  9
1631 -3.7794632e+01 6.29e+05 3.02e+01  -1.0 4.61e+06    -  6.75e-01 1.95e-03h 10
1632 -3.7795353e+01 6.28e+05 3.02e+01  -1.0 4.59e+06    -  1.00e+00 1.95e-03h 10
1633 -3.7796082e+01 6.26e+05 3.03e+01  -1.0 4.57e+06    -  6.76e-01 1.95e-03h 10
1634 -3.7796826e+01 6.25e+05 3.04e+01  -1.0 4.56e+06    -  1.00e+00 1.95e-03h 10
1635 -3.7797578e+01 6.24e+05 3.04e+01  -1.0 4.54e+06    -  6.76e-01 1.95e-03h 10
1636 -3.7798346e+01 6.23e+05 3.05e+01  -1.0 4.52e+06    -  1.00e+00 1.95e-03h 10
1637 -3.7799122e+01 6.21e+05 3.05e+01  -1.0 4.50e+06    -  6.76e-01 1.95e-03h 10
1638 -3.7799912e+01 6.20e+05 3.06e+01  -1.0 4.49e+06    -  1.00e+00 1.95e-03h 10
1639 -3.7800710e+01 6.19e+05 3.06e+01  -1.0 4.47e+06    -  6.76e-01 1.95e-03h 10
iter    objective    inf_pr 

1725 -3.7437894e+01 5.19e+05 7.08e+03  -1.0 2.24e+04  -0.6 1.13e-01 6.70e-04h  1
1726 -3.7724082e+01 5.18e+05 4.63e+04  -1.0 2.25e+04  -1.1 9.72e-03 1.49e-03h  1
1727 -4.2023598e+01 5.61e+05 1.55e+06  -1.0 2.25e+04  -1.6 7.95e-03 5.12e-02h  1
1728 -3.8385704e+01 6.45e+05 2.74e+06  -1.0 2.20e+04  -2.0 1.13e-02 8.32e-02h  1
1729 -3.7949208e+01 6.45e+05 5.24e+06  -1.0 2.34e+04  -0.7 2.13e-02 4.91e-04h  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
1730 -3.7845268e+01 6.45e+05 3.98e+07  -1.0 2.49e+04  -0.3 4.90e-02 8.87e-05h  1
1731 -3.7698557e+01 6.45e+05 8.57e+07  -1.0 2.53e+04   0.1 2.07e-02 6.25e-05h  1
1732 -3.6329758e+01 6.44e+05 1.59e+08  -1.0 2.60e+04  -0.3 1.03e-01 2.90e-04h  2
1733 -3.6189956e+01 6.33e+05 1.57e+08  -1.0 2.37e+04  -0.8 2.28e-02 1.84e-02h  1
1734 -3.6190337e+01 6.33e+05 1.74e+08  -1.0 1.52e+05  -1.3 4.98e-02 1.28e-05h  1
1735 -2.6997415e+01 6.31e+05 1.88e+08  -1.0 6.78e+04  -1.8 8.75e-02 2.80e-03h  1
1736 -2.7025374e+01 6.33e+05

In iteration 1819, 1 Slack too small, adjusting variable bound
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
1820 -3.7847247e+01 6.58e-05 8.16e+05  -8.6 1.86e-06  11.5 1.00e+00 8.18e-01h  1
In iteration 1820, 1 Slack too small, adjusting variable bound
1821 -3.7847247e+01 6.57e-05 8.15e+05  -8.6 1.99e-04  11.0 4.66e-01 8.85e-04h  1
In iteration 1821, 1 Slack too small, adjusting variable bound
1822 -3.7847247e+01 6.57e-05 1.94e+06  -8.6 2.10e-04  10.6 1.00e+00 8.47e-04h  1
In iteration 1822, 1 Slack too small, adjusting variable bound
1823 -3.7847247e+01 6.53e-05 1.93e+06  -8.6 3.39e+01    -  4.61e-03 6.12e-03h  1
1824 -3.7847247e+01 8.99e-06 5.00e+04  -8.6 4.16e-06  10.1 9.77e-01 1.00e+00h  1
In iteration 1824, 1 Slack too small, adjusting variable bound
1825 -3.7847247e+01 8.55e-06 7.49e+04  -8.6 3.25e-04   9.6 1.61e-01 4.96e-02h  1
1826 -3.7847247e+01 8.50e-06 7.68e+04  -8.6 3.09e-04   9.1 4.96e-02 5.42e-03h  2
1827 -3.7847247e+01 8.50e-06 7.68e+04

1915r-3.7847076e+01 1.16e-10 9.18e+02  -8.6 0.00e+00    -  0.00e+00 4.06e-07R 16
1916r-3.7847076e+01 1.16e-10 9.94e+00  -8.6 1.00e-01    -  9.89e-01 8.89e-02f  1
1917r-3.7847048e+01 1.10e-05 7.23e-01  -8.6 9.72e+00    -  9.27e-01 1.00e+00h  1
1918r-3.7846772e+01 8.70e-04 3.42e-01  -8.6 4.20e+01    -  5.26e-01 1.00e+00h  1
1919r-3.7846575e+01 9.90e-04 8.12e-07  -8.6 2.60e+01    -  1.00e+00 1.00e+00h  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
1920r-3.7846485e+01 1.09e-04 3.79e-08  -8.6 1.94e+00    -  1.00e+00 1.00e+00h  1
1921r-3.7846492e+01 8.22e-07 3.51e-10  -8.6 2.58e-01    -  1.00e+00 1.00e+00h  1
1922r-3.7846492e+01 1.16e-10 1.14e-13  -8.6 2.88e-03    -  1.00e+00 1.00e+00h  1
1923r-3.7846818e+01 1.52e-03 7.03e-07 -11.0 1.32e+01    -  1.00e+00 1.00e+00f  1
1924r-3.7846836e+01 4.41e-06 2.82e-08 -11.0 6.70e-01    -  1.00e+00 1.00e+00h  1
1925r-3.7846945e+01 1.86e-08 4.84e-09 -11.0 4.50e+00    -  1.00e+00 1.00e+00H  1
1926r-3.7846974e+01 1.86e-09

ValueError: Cannot load a SolverResults object with bad status: error

In [ ]:
from pyomo.core.kernel.component_set import ComponentSet

def large_residuals_set(block, tol=1e-5, LOUD=True):
    """
    Method to return a ComponentSet of all Constraint components with a
    residual greater than a given threshold which appear in a model.
    Args:
        block : model to be studied
        tol : residual threshold for inclusion in ComponentSet
    Returns:
        A ComponentSet including all Constraint components with a residual
        greater than tol which appear in block
    """
    large_residuals_set = ComponentSet()
    for c in block.component_data_objects(
            ctype=Constraint, active=True, descend_into=True):
        if c.active and value(c.lower - c.body()) > tol:
            large_residuals_set.add(c)
        elif c.active and value(c.body() - c.upper) > tol:
            large_residuals_set.add(c)
    
    if LOUD:
        print("All equality constraints with residuals larger than",tol)
        for c in large_residuals_set:
            print(c)
            
    return large_residuals_set

large_residuals_set(mod_eg, tol=1.0E-5)

In [ ]:
print('======Result summary======')
print('This optimization is solved with status:', optimize_result.status)
print('The result FIM is:', optimize_result.FIM)
print('Four design criteria log10() value:')
print('A-optimality:', np.log10(optimize_result.trace))
print('D-optimality:', np.log10(optimize_result.det))
print('E-optimality:', np.log10(optimize_result.min_eig))
print('Modified E-optimality:', np.log10(optimize_result.cond))

t_list = []
for t in optimize_result.model.t:
    t_list.append(t)

T_list = []
for i in t_list:
    T_list.append(value(optimize_result.model.T[i]))

print(value(optimize_result.model.T[0]))
print(value(optimize_result.model.T[1]))
print()
    
si=16
plt.rc('axes', titlesize=si)
plt.rc('axes', labelsize=si)
plt.rc('xtick', labelsize=si)
plt.rc('ytick', labelsize=si)
plt.rc('legend', fontsize=12)
    
plt.plot(t_list, T_list, 'b', linewidth=2)
#plt.scatter(t_list, T_list, 'b')
plt.ylabel('T [$K$]')
plt.xlabel('Time [$h$]')
plt.show()

## Method: Exploratory analysis (Enumeration)

This method conducts exploratory analysis by enumeration. 
It allows to define any number (dimensions) of design variables.
Heatmaps can be drawn by two design variables, fixing other design variables; 
1D curve can be drawn by one design variable, fixing other design variables.

### Specify user inputs

In [ ]:
# Design variable ranges as lists 
design_ranges = [list(np.linspace(1,5,5)), list(np.linspace(300,700,5))]

# Design variable names 
dv_apply_name = ['CA0','T']

# Design variable should be fixed at these time points
dv_apply_time = [[0],t_control]

# Define experiments. This is a starting point of which the value does not matter
exp1 = generate_exp(t_control, 5, [300, 300, 300, 300, 300, 300, 300, 300, 300])
    
## choose from 'sequential_finite', 'direct_kaug'
#sensi_opt = 'sequential_finite'
sensi_opt = 'direct_kaug'

# model option
if sensi_opt == 'direct_kaug':
    args_ = [False]
else:
    args_ = [True]

In [ ]:
# add prior information
prior_5_300 = pd.read_csv('fim_5_300_scale.csv')
#prior_5_300_500 = pd.read_csv('fim_5_300_500_scale.csv')

prior_all = prior_5_300

prior_pass=np.asarray(prior_all)

#L_initials = np.linalg.cholesky(prior_pass)
#print(L_initials)

print('The prior information FIM:', prior_pass)
print('Prior Det:', np.linalg.det(prior_pass))

In [ ]:
doe_object = DesignOfExperiments(parameter_dict, dv_pass,
                                 measure_class, createmod,
                                prior_FIM=prior_pass, discretize_model=disc, args=args_)

all_fim = doe_object.run_grid_search(exp1, design_ranges, dv_apply_name, dv_apply_time, 
                                     mode=sensi_opt)

### 1D sensitivity curve

In [ ]:
test = all_fim.extract_criteria()

## draw 1D sensitivity curve 

fixed = {"'CA0'": 5.0}

all_fim.figure_drawing(fixed, ['T'], 'Reactor case','T [K]','$C_{A0}$ [M]' )



## Heatmap

In [ ]:
fixed = {}
all_fim.figure_drawing(fixed, ['CA0','T'], 'Reactor case','$C_{A0}$ [M]', 'T [K]' )

## Grid search for 3 design variables

In [ ]:

# Define design ranges
design_ranges = [list(np.linspace(1,5,2)),  list(np.linspace(300,700,2)), [300,500]]

# Define design variable 
# Here the two T are for different controlling time subsets
dv_apply_name = ['CA0', 'T', 'T']
dv_apply_time = [[0], [0], [0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875,1]]

# Define experiments
exp1 = generate_exp(t_control, 5, [300, 300, 300, 300, 300, 300, 300, 300, 300])

## choose from 'sequential_finite', 'direct_kaug'
#sensi_opt = 'sequential_finite'
sensi_opt = 'direct_kaug'

# model option
if sensi_opt == 'direct_kaug':
    args_ = [False]
else:
    args_ = [True]

In [ ]:
doe_object = DesignOfExperiments(parameter_dict, dv_pass,
                                 measure_class, createmod,
                                prior_FIM=prior_pass, discretize_model=disc, args=args_)

all_fim = doe_object.run_grid_search(exp1, design_ranges, dv_apply_name, dv_apply_time, 
                                     mode=sensi_opt)

### Draw 1D sensitivity curve

In [ ]:
test = all_fim.extract_criteria()

In [ ]:
## draw 1D sensitivity curve 

fixed = {"'CA0'": 1.0, "'T2'": 300}

all_fim.figure_drawing(fixed, ['T'], 'Reactor case','T [K]','$C_{A0}$ [M]' )

### Draw 2D sensitivity curve

In [ ]:
fixed = {"'T2'": 300}

all_fim.figure_drawing(fixed, ['CA0','T'], 'Reactor case','$C_{A0}$ [M]', 'T [K]' )